class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:naam, :password, :password_confirmation, :invitation_token])
  end

  # Add this method to override Devise's default redirect
  def after_sign_in_path_for(resource)
    # 'resource' is the signed-in user.
    # This will redirect to the path generated by `dashboard_path`.
    dashboard_path
  end
end
